// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBRydoUlngcy5PpQY9YEPb_PYJOXwnxQJ0',
    appId: '1:40684053584:web:483485835737a8d7351d55',
    messagingSenderId: '40684053584',
    projectId: 'busbooker-c21df',
    authDomain: 'busbooker-c21df.firebaseapp.com',
    storageBucket: 'busbooker-c21df.appspot.com',
    measurementId: 'G-XSSGRKS39B',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDdfiq-eMJyoiIrlVcfS0tCQeJqT_dJ4_Q',
    appId: '1:40684053584:android:035dceaddc640f3c351d55',
    messagingSenderId: '40684053584',
    projectId: 'busbooker-c21df',
    storageBucket: 'busbooker-c21df.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAKRQvd67JHv40W12GTFKMEmG-SQxdIpQ8',
    appId: '1:40684053584:ios:2e5ad8c7f71ff912351d55',
    messagingSenderId: '40684053584',
    projectId: 'busbooker-c21df',
    storageBucket: 'busbooker-c21df.appspot.com',
    iosClientId: '40684053584-4qdgljjs5ktesgao1snfm89geejt85fo.apps.googleusercontent.com',
    iosBundleId: 'com.example.edustore',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAKRQvd67JHv40W12GTFKMEmG-SQxdIpQ8',
    appId: '1:40684053584:ios:92a66ae0a12c26ad351d55',
    messagingSenderId: '40684053584',
    projectId: 'busbooker-c21df',
    storageBucket: 'busbooker-c21df.appspot.com',
    iosClientId: '40684053584-4ircbebjhoojjoicv3j0pv780thrcne9.apps.googleusercontent.com',
    iosBundleId: 'com.example.edustore.RunnerTests',
  );
}
